
spring:
  application:
    name: "loans"
  profiles:
    active: "default"
#  datasource:
#    url: jdbc:h2:mem:testLoansdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
  datasource:
    url: jdbc:mysql://localhost:3306/loansdb?createDatabaseIfNotExist=true
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
server:
  port: 5051
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # this configuration allows actuator to expose info related properties
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true



# this root configuration allows to shut down the service via actuator
# http://localhost:5050/actuator/shutdown
endpoints:
  shutdown:
    enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    # this is self-explanatory
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
info:
  app:
    name: "loans"
    description: "Eazy bank loans application"
    version: 1
