accounts:
  message: "Welcome to the EazyBank accounts related local APIs"
  contactDetails:
    name: "Balaji"
    email: "ballanibalaji@gmail.com"
  onCallSupport:
    -(91) 9491277098
    -(91) 9948112882
build:
  version: local version 3.0
management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

