accounts:
  message: "Welcome to the EazyBank accounts related QA APIs"
  contactDetails:
    name: "Balaji"
    email: "ballanibalaji@gmail.com"
  onCallSupport:
    -(91) 9491277098
    -(91) 9948112882
build:
  version: QA version 3.0